### ISSUE TITLE
После загрузки трека показатели нулевые

### ISSUE THREAD

**Issue by denissakharov** [yamax2/gpxstorage#3]
Сразу после загрузки трека отображается таблица в которой расстояние и средняя скорость равны нулю
![screen shot 2016-09-02 at 07 47 13](https://cloud.githubusercontent.com/assets/11212927/18191373/961be6f0-70eb-11e6-9302-7f23ffe6c2b5.png)

правильные данные можно увидеть только после обновления страницы
![screen shot 2016-09-02 at 07 47 26](https://cloud.githubusercontent.com/assets/11212927/18191410/d8950d04-70eb-11e6-8c5e-de5d7872a799.png)

**Comment by yamax2** [comment]
это так задумано, операция довольно небыстрая
